"""
Medical Imaging Analysis Application

A local, privacy-preserving Streamlit app for analyzing X-rays, CTs, and MRIs
using a local Vision-Language Model via Ollama or mlx-lm.
"""

import streamlit as st
from PIL import Image

from inference import MlxLmBackend, OllamaBackend
from preprocessing import (
    dicom_to_pil,
    load_dicom,
    preprocess_dicom,
    preprocess_standard_image,
)

DISCLAIMER = (
    "**⚕️ PROVISIONAL FINDINGS — NOT A MEDICAL DIAGNOSIS**\n\n"
    "The analysis below is generated by an AI model and is provided for "
    "informational and educational purposes only. It has **not** been reviewed "
    "or verified by a licensed physician. **Do not** use this output to make "
    "clinical decisions. Always consult a qualified healthcare professional "
    "for medical advice, diagnosis, or treatment."
)

RECOMMENDED_VISION_MODELS = [
    "llama3.2-vision",
    "llava",
    "llava-phi3",
    "bakllava",
    "moondream",
    "minicpm-v",
    "granite3.2-vision",
    "qwen2.5vl",
    "gemma3",
]


def init_session_state():
    defaults = {
        "analysis_results": {},
        "acknowledged": False,
        "pull_status": None,
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val


def _format_size(size_bytes):
    """Format byte count to human-readable string."""
    for unit in ("B", "KB", "MB", "GB"):
        if abs(size_bytes) < 1024:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024
    return f"{size_bytes:.1f} TB"


def render_sidebar():
    """Render the sidebar with backend configuration."""
    st.sidebar.header("Backend Configuration")

    backend_choice = st.sidebar.radio(
        "Inference Backend",
        ["Ollama (Recommended)", "mlx-lm (Apple Silicon)"],
        index=0,
    )

    if backend_choice.startswith("Ollama"):
        ollama_url = st.sidebar.text_input("Ollama URL", value="http://localhost:11434")
        ollama_model = st.sidebar.text_input(
            "Ollama Model",
            value="llama3.2-vision",
            help="Vision-capable model name (e.g., llama3.2-vision, llava)",
        )
        backend = OllamaBackend(model_name=ollama_model, base_url=ollama_url)

        if st.sidebar.button("Check Connection"):
            if backend.is_available():
                st.sidebar.success(f"Connected. Model '{ollama_model}' is available.")
            else:
                models = backend.list_model_names()
                if models:
                    st.sidebar.warning(
                        f"Model '{ollama_model}' not found. Available: {', '.join(models)}"
                    )
                else:
                    st.sidebar.error("Cannot connect to Ollama. Is it running?")
    else:
        mlx_model = st.sidebar.text_input(
            "mlx-lm Model",
            value="mlx-community/GLM-4.5V-9B-4bit",
            help="Hugging Face model ID for mlx-lm",
        )
        backend = MlxLmBackend(model_name=mlx_model)

        if st.sidebar.button("Check Availability"):
            if backend.is_available():
                st.sidebar.success("mlx-lm is installed and ready.")
            else:
                st.sidebar.error("mlx-lm is not installed. Run: pip install mlx-lm")

    st.sidebar.markdown("---")
    st.sidebar.markdown(
        "🔒 **Privacy**: All processing runs locally.\n\n"
        "No data is sent to external servers."
    )

    return backend


def render_model_management(backend):
    """Render the Ollama model management tab."""
    if not isinstance(backend, OllamaBackend):
        st.info("Model management is only available with the Ollama backend.")
        return

    st.subheader("Ollama Model Management")

    # Connection check — list_models() returns None on connection failure,
    # or an empty list when connected but no models are installed.
    models = backend.list_models()
    if models is None:
        st.error(
            "Cannot connect to Ollama. Make sure Ollama is running "
            "(`ollama serve` or the desktop app)."
        )
        return

    # --- Installed Models ---
    st.markdown("#### Installed Models")
    if models:
        for model in models:
            name = model.get("name", "unknown")
            size = _format_size(model.get("size", 0))
            details = model.get("details", {})
            param_size = details.get("parameter_size", "?")
            quant = details.get("quantization_level", "?")
            family = details.get("family", "?")

            col1, col2, col3 = st.columns([3, 2, 1])
            with col1:
                st.markdown(f"**{name}**")
                st.caption(f"{family} · {param_size} · {quant} · {size}")
            with col2:
                if st.button("ℹ️ Info", key=f"info_{name}"):
                    info = backend.show_model(name)
                    if info:
                        st.json({
                            "family": info.get("details", {}).get("family"),
                            "parameter_size": info.get("details", {}).get("parameter_size"),
                            "quantization": info.get("details", {}).get("quantization_level"),
                            "template": info.get("template", "")[:200] + "...",
                        })
            with col3:
                if st.button("🗑️ Delete", key=f"del_{name}"):
                    if backend.delete_model(name):
                        st.success(f"Deleted {name}")
                        st.rerun()
                    else:
                        st.error(f"Failed to delete {name}")
        st.markdown("---")
    else:
        st.info("No models installed. Pull one below to get started.")

    # --- Running Models ---
    running = backend.list_running()
    if running:
        st.markdown("#### Currently Loaded")
        for model in running:
            name = model.get("name", "unknown")
            vram = _format_size(model.get("size_vram", 0))
            st.caption(f"🟢 **{name}** — VRAM: {vram}")
        st.markdown("---")

    # --- Pull New Model ---
    st.markdown("#### Pull New Model")

    pull_col1, pull_col2 = st.columns([3, 1])
    with pull_col1:
        model_to_pull = st.text_input(
            "Model name",
            placeholder="e.g., llama3.2-vision",
            help="Enter an Ollama model name from ollama.com/library",
        )
    with pull_col2:
        st.markdown("")  # spacing
        pull_clicked = st.button("⬇️ Pull Model", type="primary")

    if pull_clicked and model_to_pull:
        progress_bar = st.progress(0, text=f"Pulling {model_to_pull}...")
        status_text = st.empty()
        try:
            for update in backend.pull_model(model_to_pull):
                status = update.get("status", "")
                completed = update.get("completed", 0)
                total = update.get("total", 0)
                if total > 0:
                    pct = min(completed / total, 1.0)
                    progress_bar.progress(
                        pct,
                        text=f"{status} — {_format_size(completed)} / {_format_size(total)}",
                    )
                else:
                    status_text.caption(status)
            progress_bar.progress(1.0, text="Download complete!")
            st.success(f"Successfully pulled {model_to_pull}")
            st.rerun()
        except Exception as e:
            st.error(f"Failed to pull model: {e}")

    # --- Recommended Models ---
    with st.expander("Recommended Vision Models"):
        st.markdown(
            "These models support image analysis on Ollama:\n\n"
            + "\n".join(f"- `{m}`" for m in RECOMMENDED_VISION_MODELS)
            + "\n\nCopy a name above and click **Pull Model** to download."
        )


MAX_UPLOADS = 3


def _process_uploaded_file(uploaded_file):
    """Process a single uploaded file into (image_8bit, pil_image, metadata).

    Raises on failure so the caller can report per-file errors.
    """
    file_name = uploaded_file.name.lower()
    is_dicom = file_name.endswith((".dcm", ".dicom"))

    if is_dicom:
        ds = load_dicom(uploaded_file)
        image_8bit, metadata = preprocess_dicom(ds)
        pil_image = dicom_to_pil(image_8bit)
    else:
        image_array, metadata = preprocess_standard_image(uploaded_file)
        image_8bit = image_array
        pil_image = Image.fromarray(image_array)

    return image_8bit, pil_image, metadata


def render_upload_section():
    """Render the file upload area and return processed image data.

    Returns a list of (image_8bit, pil_image, metadata) tuples, one per
    successfully loaded file.  Returns an empty list when nothing is uploaded.
    """
    st.subheader("Upload Medical Images")
    uploaded_files = st.file_uploader(
        f"Upload up to {MAX_UPLOADS} DICOM (.dcm / .DCM), PNG, or JPEG files",
        type=["dcm", "DCM", "dicom", "DICOM", "png", "jpg", "jpeg"],
        accept_multiple_files=True,
    )

    if not uploaded_files:
        return []

    if len(uploaded_files) > MAX_UPLOADS:
        st.warning(
            f"Only the first {MAX_UPLOADS} files will be processed. "
            f"You uploaded {len(uploaded_files)}."
        )
        uploaded_files = uploaded_files[:MAX_UPLOADS]

    results = []
    for idx, uploaded_file in enumerate(uploaded_files):
        try:
            image_8bit, pil_image, metadata = _process_uploaded_file(uploaded_file)
        except Exception as e:
            st.error(f"Failed to load {uploaded_file.name}: {e}")
            continue

        st.markdown(f"---\n#### Image {idx + 1}: {uploaded_file.name}")
        col1, col2 = st.columns(2)
        with col1:
            st.image(pil_image, caption=uploaded_file.name, use_container_width=True)
        with col2:
            if metadata:
                st.markdown("**DICOM Metadata**")
                for k, v in metadata.items():
                    if k not in ("PatientID", "PatientName"):
                        st.text(f"{k}: {v}")
                if st.checkbox(
                    "Show patient identifiers",
                    key=f"show_ids_{idx}",
                ):
                    for k in ("PatientID", "PatientName"):
                        if k in metadata:
                            st.text(f"{k}: {metadata[k]}")
            else:
                st.info("No DICOM metadata (standard image file).")

        results.append((image_8bit, pil_image, metadata, uploaded_file.name))

    return results


def render_analysis_section(backend, images):
    """Render the analysis controls and results.

    Parameters
    ----------
    backend : OllamaBackend | MlxLmBackend
    images : list[tuple]
        Each element is (image_8bit, pil_image, metadata, file_name).
    """
    st.subheader("AI Analysis")

    user_prompt = st.text_area(
        "Additional context or question (optional)",
        value="Analyze this medical image following the 4-step diagnostic framework.",
        height=80,
    )

    if st.button("🔍 Run Analysis", type="primary"):
        if not backend.is_available():
            st.error(
                "The selected backend is not available. "
                "Please check your configuration in the sidebar."
            )
            return

        results = {}
        for image_8bit, _pil, metadata, file_name in images:
            with st.spinner(f"Analyzing {file_name}..."):
                try:
                    result = backend.analyze(
                        image_8bit,
                        user_prompt=user_prompt,
                        metadata=metadata,
                    )
                    results[file_name] = result
                except Exception as e:
                    st.error(f"Analysis failed for {file_name}: {e}")

        if results:
            st.session_state["analysis_results"] = results
            st.session_state["acknowledged"] = False

    # Display results with governor pattern
    if st.session_state["analysis_results"]:
        st.markdown("---")

        if not st.session_state["acknowledged"]:
            st.warning(DISCLAIMER)
            if st.button("I understand — show provisional findings"):
                st.session_state["acknowledged"] = True
                st.rerun()
        else:
            st.info(
                "**Provisional AI Findings** — Not reviewed by a physician. "
                "See disclaimer above."
            )
            st.markdown(DISCLAIMER)
            st.markdown("---")

            for file_name, result in st.session_state["analysis_results"].items():
                with st.expander(f"Technical Findings — {file_name}", expanded=True):
                    st.markdown(result)

                with st.expander(f"Patient-Friendly Summary — {file_name}"):
                    st.markdown(_generate_patient_summary(result))


def _generate_patient_summary(technical_result):
    """Wrap technical results in patient-friendly framing."""
    return (
        "### What This Means for You\n\n"
        "The AI has reviewed your medical image and provided observations below. "
        "Please remember:\n\n"
        "- These findings are **preliminary** and generated by a computer.\n"
        "- Only a qualified doctor can provide an actual diagnosis.\n"
        "- If the AI recommended seeing a specialist, please schedule an "
        "appointment with your primary care provider as a first step.\n"
        "- Bring this report to your doctor — it may help them in their evaluation.\n\n"
        "---\n\n"
        f"{technical_result}"
    )


def main():
    st.set_page_config(
        page_title="Medical Imaging Analysis",
        page_icon="🏥",
        layout="wide",
    )

    st.title("🏥 Medical Imaging Analysis")
    st.caption("Local, privacy-preserving AI analysis of X-rays, CTs, and MRIs")

    init_session_state()
    backend = render_sidebar()

    tab_analyze, tab_models = st.tabs(["📋 Analysis", "⚙️ Model Management"])

    with tab_analyze:
        images = render_upload_section()

        if images:
            render_analysis_section(backend, images)
        else:
            st.info("Upload a medical image to get started.")

            with st.expander("Supported Formats & Features"):
                st.markdown(
                    "**Supported file types:** DICOM (.dcm), PNG, JPEG\n\n"
                    "**Preprocessing pipeline (DICOM):**\n"
                    "- HU Calibration for CT scans\n"
                    "- Windowing (Window Center / Window Width)\n"
                    "- Photometric inversion (MONOCHROME1 → MONOCHROME2)\n\n"
                    "**AI Analysis Framework:**\n"
                    "1. Modality Identification\n"
                    "2. Structured Observations\n"
                    "3. Diagnostic Synthesis with confidence scoring\n"
                    "4. Specialist Referral Recommendations\n\n"
                    "**Backends:** Ollama (cross-platform) or mlx-lm (Apple Silicon)"
                )

    with tab_models:
        render_model_management(backend)


if __name__ == "__main__":
    main()
