"""
Medical Imaging Analysis Application

A local, privacy-preserving Streamlit app for analyzing X-rays, CTs, and MRIs
using a local Vision-Language Model via Ollama or mlx-lm.
"""

import io

import numpy as np
import streamlit as st
from PIL import Image

from inference import OllamaBackend, MlxLmBackend, SYSTEM_PROMPT
from preprocessing import (
    load_dicom,
    extract_metadata,
    preprocess_dicom,
    preprocess_standard_image,
    dicom_to_pil,
)

DISCLAIMER = (
    "**⚕️ PROVISIONAL FINDINGS — NOT A MEDICAL DIAGNOSIS**\n\n"
    "The analysis below is generated by an AI model and is provided for "
    "informational and educational purposes only. It has **not** been reviewed "
    "or verified by a licensed physician. **Do not** use this output to make "
    "clinical decisions. Always consult a qualified healthcare professional "
    "for medical advice, diagnosis, or treatment."
)


def init_session_state():
    defaults = {
        "analysis_result": None,
        "acknowledged": False,
        "image_data": None,
        "metadata": None,
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val


def render_sidebar():
    """Render the sidebar with backend configuration."""
    st.sidebar.header("Backend Configuration")

    backend_choice = st.sidebar.radio(
        "Inference Backend",
        ["Ollama (Recommended)", "mlx-lm (Apple Silicon)"],
        index=0,
    )

    if backend_choice.startswith("Ollama"):
        ollama_url = st.sidebar.text_input("Ollama URL", value="http://localhost:11434")
        ollama_model = st.sidebar.text_input(
            "Ollama Model",
            value="llama3.2-vision",
            help="Vision-capable model name (e.g., llama3.2-vision, llava)",
        )
        backend = OllamaBackend(model_name=ollama_model, base_url=ollama_url)

        if st.sidebar.button("Check Connection"):
            if backend.is_available():
                st.sidebar.success(f"Connected. Model '{ollama_model}' is available.")
            else:
                models = backend.list_models()
                if models:
                    st.sidebar.warning(
                        f"Model '{ollama_model}' not found. Available: {', '.join(models)}"
                    )
                else:
                    st.sidebar.error("Cannot connect to Ollama. Is it running?")
    else:
        mlx_model = st.sidebar.text_input(
            "mlx-lm Model",
            value="mlx-community/GLM-4.5V-9B-4bit",
            help="Hugging Face model ID for mlx-lm",
        )
        backend = MlxLmBackend(model_name=mlx_model)

        if st.sidebar.button("Check Availability"):
            if backend.is_available():
                st.sidebar.success("mlx-lm is installed and ready.")
            else:
                st.sidebar.error("mlx-lm is not installed. Run: pip install mlx-lm")

    st.sidebar.markdown("---")
    st.sidebar.markdown(
        "🔒 **Privacy**: All processing runs locally.\n\n"
        "No data is sent to external servers."
    )

    return backend


def render_upload_section():
    """Render the file upload area and return processed image data."""
    st.subheader("Upload Medical Image")
    uploaded_file = st.file_uploader(
        "Upload a DICOM (.dcm), PNG, or JPEG file",
        type=["dcm", "dicom", "png", "jpg", "jpeg"],
    )

    if uploaded_file is None:
        return None, None, None

    file_name = uploaded_file.name.lower()
    is_dicom = file_name.endswith((".dcm", ".dicom"))

    if is_dicom:
        ds = load_dicom(uploaded_file)
        image_8bit, metadata = preprocess_dicom(ds)
        pil_image = dicom_to_pil(image_8bit)
    else:
        image_array, metadata = preprocess_standard_image(uploaded_file)
        image_8bit = image_array
        pil_image = Image.fromarray(image_array)

    col1, col2 = st.columns(2)
    with col1:
        st.image(pil_image, caption="Uploaded Image", use_container_width=True)
    with col2:
        if metadata:
            st.markdown("**DICOM Metadata**")
            for k, v in metadata.items():
                # Omit patient-identifying info from default display
                if k not in ("PatientID", "PatientName"):
                    st.text(f"{k}: {v}")
            if st.checkbox("Show patient identifiers"):
                for k in ("PatientID", "PatientName"):
                    if k in metadata:
                        st.text(f"{k}: {metadata[k]}")
        else:
            st.info("No DICOM metadata (standard image file).")

    return image_8bit, pil_image, metadata


def render_analysis_section(backend, image_8bit, metadata):
    """Render the analysis controls and results."""
    st.subheader("AI Analysis")

    user_prompt = st.text_area(
        "Additional context or question (optional)",
        value="Analyze this medical image following the 4-step diagnostic framework.",
        height=80,
    )

    if st.button("🔍 Run Analysis", type="primary"):
        if not backend.is_available():
            st.error(
                "The selected backend is not available. "
                "Please check your configuration in the sidebar."
            )
            return

        with st.spinner("Analyzing image — this may take a minute..."):
            try:
                result = backend.analyze(
                    image_8bit,
                    user_prompt=user_prompt,
                    metadata=metadata,
                )
                st.session_state["analysis_result"] = result
                st.session_state["acknowledged"] = False
            except Exception as e:
                st.error(f"Analysis failed: {e}")
                return

    # Display results with governor pattern
    if st.session_state["analysis_result"]:
        st.markdown("---")

        # Disclaimer gate
        if not st.session_state["acknowledged"]:
            st.warning(DISCLAIMER)
            if st.button("I understand — show provisional findings"):
                st.session_state["acknowledged"] = True
                st.rerun()
        else:
            st.info(
                "**Provisional AI Findings** — Not reviewed by a physician. "
                "See disclaimer above."
            )
            st.markdown(DISCLAIMER)
            st.markdown("---")

            # Technical findings
            with st.expander("Technical Findings", expanded=True):
                st.markdown(st.session_state["analysis_result"])

            # Patient-friendly summary
            with st.expander("Patient-Friendly Summary"):
                st.markdown(
                    _generate_patient_summary(st.session_state["analysis_result"])
                )


def _generate_patient_summary(technical_result):
    """Wrap technical results in patient-friendly framing."""
    return (
        "### What This Means for You\n\n"
        "The AI has reviewed your medical image and provided observations below. "
        "Please remember:\n\n"
        "- These findings are **preliminary** and generated by a computer.\n"
        "- Only a qualified doctor can provide an actual diagnosis.\n"
        "- If the AI recommended seeing a specialist, please schedule an "
        "appointment with your primary care provider as a first step.\n"
        "- Bring this report to your doctor — it may help them in their evaluation.\n\n"
        "---\n\n"
        f"{technical_result}"
    )


def main():
    st.set_page_config(
        page_title="Medical Imaging Analysis",
        page_icon="🏥",
        layout="wide",
    )

    st.title("🏥 Medical Imaging Analysis")
    st.caption("Local, privacy-preserving AI analysis of X-rays, CTs, and MRIs")

    init_session_state()
    backend = render_sidebar()
    image_8bit, pil_image, metadata = render_upload_section()

    if image_8bit is not None:
        render_analysis_section(backend, image_8bit, metadata)
    else:
        st.info("Upload a medical image to get started.")

        # Show supported formats
        with st.expander("Supported Formats & Features"):
            st.markdown(
                "**Supported file types:** DICOM (.dcm), PNG, JPEG\n\n"
                "**Preprocessing pipeline (DICOM):**\n"
                "- HU Calibration for CT scans\n"
                "- Windowing (Window Center / Window Width)\n"
                "- Photometric inversion (MONOCHROME1 → MONOCHROME2)\n\n"
                "**AI Analysis Framework:**\n"
                "1. Modality Identification\n"
                "2. Structured Observations\n"
                "3. Diagnostic Synthesis with confidence scoring\n"
                "4. Specialist Referral Recommendations\n\n"
                "**Backends:** Ollama (cross-platform) or mlx-lm (Apple Silicon)"
            )


if __name__ == "__main__":
    main()
